### ISSUE TITLE
Problem with site who in BETA2

### ISSUE THREAD

**Issue by teqnodude** [glftpd/glftpd#26] opened 2019-12-07 19:34 UTC
I get this error message when doing the command site who in BETA2

`550 ASSERT: (srclen + 1 <= dest_size) in file pids.c line 781 inside function gl_strcpy_internal`

**Comment by teqnodude** [comment] 2019-12-08 08:30
Now I don't get it anymore all of a sudden, have no idea what caused it.

**Comment by glftpd** [comment] 2019-12-08 14:40
caused by file names longer then 12 chars. will be fixed in next beta

**Closed as completed** 2019-12-08 17:21 UTC
