### ISSUE TITLE
"ghost" 0byte bug

### ISSUE THREAD

**Issue by Termin8or666** [glftpd/glftpd#28] opened 2019-12-09 21:37 UTC
Hi
I have been observing 0byte files on many sites.. even in current version 2.10

info before i ramble on

all connection speeds affected
100mbit -> 10gbit
Can happen with 1 user or 100
No high load on servers but its when incoming is pumping to 75%+
probably all version affected but I noticed this from 2.06-2.10
0byte file is not logged anywhere its like the connection never occured.
multiple clients / ssl versions tested with same results

When a file is uploaded and stuck on 0byte (seems like a ssl handshake gone wrong)
its all fine if there is a connection (pid) holding it, kill pid with a script sweeping for 0bytes and all good.
Connection killed = zipscript cleanup of the file
Here is where it gets tricky.. when a 0byte file is held, you can see the username of the user holding it but there are no connections, not even a ghost connection (thats why I call them ghost 0bytes) glftpd will timeout this file eventually.. could happen in 2 minutes or 25..
If I could compare that timeout behavior it would be to the sleep on bad function in pzs-ng.
This slows down races or worst case leave the release incomplete at 99% because racers stopped rechecking rls when last file was locked for say max 30minutes if not handled by a 0byte script.

IF you have a script detect and wipe that file that has no pid associated with it,... there is a HIGH chance that with todays connection speeds it would be replaced within seconds.. and when glftpd finally times out, it would wipe the complete file and you end up with a release marked 100% complete but missing a file, only workaround atm to avoid this is to have a 0byte loop register the files its wiping and adding that release to a delayed rescan to make sure it is infact complete for archiving.

To me this looks like hardcoded behaviour in the source code as ive poked every angle of this that I can think of.
Hopefully there will be more reports of this after this bug report.. most of the time people dont know they have 0byte problems they just think a release was 99% uploaded as there are nothing useful in the logs to explain it otherwise.

Good work on the new version as always=)

**Comment by glftpd** [comment] 2019-12-10 12:06
so 2 issues.
1. sometimes gl is holding a 0 byte file for too long
2. while holding it, your script cannot figure out which gl process is holding it

Either way we need to figure out when and how this happens. For 1) it can be all kind of weird uploader behaviour causing the server to keep waiting but not actually pushing any files. The normal timeout for these thigns in gl is 120 seconds. I cant see how it could be more but if someone can replicate let me know. Im not sure if this can be somehow lowered if the uploader is doing this on purpose but at least in 2.10 we now find out if the client disconnected or tried to ABOR.

As for 2) again it would be very helpful to replicate somehow but if you can confirm that those scripts use SHM structures and find the STOR command with matching filename then i can check something.

**Comment by Termin8or666** [comment] 2019-12-10 14:52
ive seen that 120sec limit in an old changelog so ive set the script not to touch the file before its atleast 2minutes old, I have also tried making the script log in and wipe it from ftpd istead of shell to see if it kills the timeout but it does not. (sometimes the complete file is wiped 20mins later)
my script uses tur-ftpwho to identify pid, and that works every time when there is an actual connection holding the file at 0byte.. 
problem is when those ghost 0bytes occur.. user who then holds the file at 0bytes is nowhere to be associated to that file, ive manually checked that same user is uploading new files on all slots he has available. That internal glftpd phantom is hard to crack :) 
Id say 0byte with actual pid to kill is 70% of the time and 30% ghost, its easier to spot on a 90gb UHD race but it happens on all file sizes.

**Comment by glftpd** [comment] 2019-12-10 15:24
could it be maybe related to a user logging again with !username and killing his previous session at some weird moment causing the 0byte file ? i would suggest that you stop the cleanup script see if the issue can still happen. when you see a 0byte file for long try to find a matching glftpd and maybe make a dump, since the file gets eventually deleted there must be a glftpd process hanging there somehow :) would be interesting to see its gl_spy record also

**Comment by Termin8or666** [comment] 2019-12-10 15:45
Will try to dig in and find a process to match it to.. hard to do as its not logged anywhere and the timeframe of the timeout varies from 2-20 minutes
I run killghost before the script wipes the file found after 2 minutes, but it does not find any ghost connections at that point. Ive set an irc announce for the files found and there are some every day. As said when connection load hits 75-100% its more often, could it be some overflow when accepting ssl handshakes for a file causing the "timeout"?

**Comment by glftpd** [comment] 2019-12-10 17:12
maybe change the killghost script to dump the process first before killing if it lasted more then 2min. IF there are processes which are holding the file/will delete it later but you cannot figure out which one did it then dump all gl processes to files and use strace logging to find out which PID eventually deleted the file.

**Comment by glftpd** [comment] 2019-12-10 17:13
if you wanna do those dumps its better i get you a binary with symbols so poke hujer on efnet. I can even add some debug log messages to help you tracking down the thing.

**Comment by Termin8or666** [comment] 2019-12-10 18:35
sounds great :) wouldnt surprise me if this turned out to be a zipscript bug in the end

**Comment by teqnodude** [comment] 2019-12-10 18:52
It may be related to this issue that I started on pzs-ng.

"Headdata.lock and rescan issue"
https://github.com/pzs-ng/pzs-ng/issues/30

**Comment by Termin8or666** [comment] 2019-12-13 07:58
As there are no indication of an active transfer (nor any log acivity of any kind) for those ghost 0bytes im curious how does glftpd handle the 120sec limit internally?
could you make it check if there are any pids related to the connection killed and make sure its killed? even double check that the file related still is 0 bytes and if so remove it ?
And if zipscript is to blame holding it could you somehow make glftpd terminate that link to the file?

**Comment by glftpd** [comment] 2019-12-13 11:16
each gl process represents one user session. one of the sessions would be uploading the 0byte file and it either dissapears and leaves the file there or its still there waiting until some timeout or something. That would be the first thing to find out. Using a strace on xinetd and make it follow its children you shoudl be able to find out what actually happens with the file. who creates it and who eventually deletes it. whether its the same process or not.

we cant really check for other pids or anything like that. the process is only responsible for its own things.

**Comment by Termin8or666** [comment] 2019-12-13 22:10
Great idea, I see that strace would be huge so have to trigger it for some minutes when a 0byte is found and older than the 120s glftpd limit, that would probably just give us insight of the activity of the pid when holding the file.. would that give you some ideas or do you need the strace when the file is first created ?

**Comment by Termin8or666** [comment] 2019-12-14 22:33
timeout 2m strace -f -tt -o /tmp/glftpd.trace -p `pidof glftpd | tr ' ' ','`       dumping that during a race would result in a 500mb+ file

timeout 1m strace -ff -tt -o /DEBUG/test -p `pidof glftpd | tr ' ' ','`     results in ALOT of files for each pid.

any idea how I could get a "cleaner" output?
if not I can try to strace a known pid holding a 0byte altho they are not the ghost we are chasing :)

**Comment by glftpd** [comment] 2019-12-15 16:24
well yeah it will be huge we can filter it out later. start it on inetd with -f and if space is an issue have it stopped every few min to rename the log file and zip the old log file. like logrotate does

once the issue happens you can cut out the relevant parts

**Comment by Termin8or666** [comment] 2019-12-15 20:10
I will setup a loop for the debug, dumping a new file every minute so its not unmanagable :)

**Comment by Termin8or666** [comment] 2019-12-15 22:10
seems like glftpd does not like to be straced for too long, after 20minutes or so it denies new connections so permanent strace to track this is no good.

**Comment by Termin8or666** [comment] 2019-12-16 23:20
I managed to strace when the file was over 2 minutes old but timed out before 3 minutes old
at the start there are alot of these:

alarm(120 <unfinished ...>
alarm(120)        = 120

when the file is still 0byte:
22541 17:29:10.248956 lstat("xxxx.r45",  <unfinished ...>
22541 17:29:10.248977 <... lstat resumed> {st_mode=S_IFREG|0755, st_size=0, ...}) = 0


12369 17:29:10.249383 readlink("xxxx.r45",  <unfinished ...>
12369 17:29:10.249403 <... readlink resumed> 0x7ffcfb8f73b0, 4096) = -1 EINVAL (Invalid argument)

350mb dump for 1 minute, any specific commands I should look for ?

**Comment by Termin8or666** [comment] 2019-12-21 21:15
rambling some thoughts as it never reaches any logs

openssl / tcp issue as its happening from 75%-100% bandwith load, altho no real load on servers
does not happen with manual transfers (example with flashfxp sessions 20tb to archive and you will never see a 0byte, if anything a normal bad crc)
only happens during a race with multiple sessions / threads
client issue? ..slftp
issue from a source .. drftpd comes to mind here.
zipscript issue
predircheck script bug ? dont think this is relevant since manual transfers are all ok
socket opens, makes file but data never passes through
side effect of the built in anti 0byte?  BAD_FILE_0SIZE altho those are logged and never the same file as the ghost 0bytes

will do some more debugging when I have the time... hopefully more people can share similar behavior as this rabbit hole seems to be DEEP

**Comment by Termin8or666** [comment] 2019-12-22 20:42
When comparing timestamps to error.log
Panic: SSL_ERROR_SYSCALL in tls_write()!
More info: Broken pipe

**Comment by steakboy7000** [comment] 2019-12-24 22:18
> When comparing timestamps to error.log
> Panic: SSL_ERROR_SYSCALL in tls_write()!
> More info: Broken pipe

That looks like a disconnect by the source site during TLS handhake to me, since the handshake would be the only point during an upload where tls_write is called. When that happens there is indeed nothing logged. I tried to reproduce it with a script but I can't seem to trigger a broken pipe error (happens when writing on a socket that was closed by the remote end).

**Comment by Termin8or666** [comment] 2019-12-26 00:56
Would it be possible to add better ssl / socket error handling to avoid this?

**Comment by glftpd** [comment] 2019-12-26 17:32
Still this might just be a consequence of the issue. Im thinking maybe a timeout eventually happens and the timeout handler tries to write something to the disconnected client before the zipscript/file cleanup. If the writing to client fails we drop the connection and leave the file there? Some scenario like that is certainly possible i think but im not sure how it can happen that gl wouldnt notice the disconnect until it tries to write to the client... It must assume connection is ok since a timeout happens and then it notices the connection is broken when handling the timeout maybe...

**Comment by Termin8or666** [comment] 2019-12-26 20:38
yeah weird indeed, the timeout happens between 2-25 minutes if the file is not wiped, and if wiped the timeout could delete the complete file. I would say that happens around 10% of the time so not that often.

**Comment by Termin8or666** [comment] 2019-12-27 21:10
0byte with pid (killed) to speed up race (will disable for debug)

store() before dataconn , (makes the 0byte)

Last command was STOR ( when pid is killed )

normal when all is fine:

store() before dataconn
data TLS connection using cipher ECDHE-ECDSA-AES256-GCM-SHA384 (version TLSv1.2) (256 bits)
data TLS data connection reused status : no
data TLS compression status NONE, Expansion NONE
ul normal
store() after receive_data 
store() done: 
store() done will testfile() : , receiveres 0, filecrc 


still waiting for a ghost 0byte to be logged

**Comment by Termin8or666** [comment] 2019-12-28 10:03
Here we have a ghost 0byte log:

Sat Dec 28 08:38:06 2019 [1893    ] got session reusable 1

Looks like there were 2 pids trying to start transfer on the same file:
Sat Dec 28 08:45:03 2019 [1895    ] store() before dataconn /site/example.r28
Sat Dec 28 08:45:03 2019 [1895    ] SSL_accept(): (5) error:00000000:lib(0):func(0):reason(0)
Sat Dec 28 08:45:04 2019 [1893    ] SSL_accept(): (5) error:00000000:lib(0):func(0):reason(0)
Sat Dec 28 08:45:05 2019 [1893    ] store() before dataconn /site/example.r28


This is when file times out and gets deleted on its own:
Sat Dec 28 09:00:05 2019 [1893    ] toolong() with timeout of 900   


unrelated to the file but this happens sometimes when socket is reused:

Sat Dec 28 09:37:12 2019 [1895    ] is resumable
Sat Dec 28 09:37:12 2019 [1895    ] SSL_connect(): (1) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure




example #2
Sat Dec 28 03:22:07 2019 [21880   ] is resumable
Sat Dec 28 03:22:07 2019 [21880   ] got session reusable 1

Sat Dec 28 03:31:01 2019 [21880   ] SSL_accept(): (5) error:00000000:lib(0):func(0):reason(0)

Sat Dec 28 03:31:02 2019 [21880   ] store() before dataconn /site/example.r21

Sat Dec 28 03:46:02 2019 [21880   ] toolong() with timeout of 900

**Comment by glftpd** [comment] 2019-12-28 23:22
thx, ill rewrite how the connection is created so it has a proper timeout support during ssl handshake

**Comment by glftpd** [comment] 2019-12-30 13:04
thanks for the help Termin8or666. should be fixed in next release

**Closed as completed by glftpd** 2019-12-30 13:04 UTC
