### ISSUE TITLE
Data connection is not always closed on control disconnect

### ISSUE THREAD

**Issue by steakboy7000** [glftpd/glftpd#15] opened 2019-07-07 22:05 UTC
When an upload has been started (i.e. STOR has been executed and its first response has been sent) but no data has yet been transmitted, closing the control connection will not close the data connection.
The file will remain as 0 bytes as long as the data connection isn't closed on the peer end.
This happens regardless of whether port or pasv was used.

The data connection will be closed whenever any data arrives as glftpd will then realize that the control connection is gone.
This causes troubles for example during FXP when the other site runs out of credits and the STOR (successful) was executed before the RETR (unsuccessful). The only way to stop the transfer is then to close the data connection on the other site.

Sending ABOR will not work either in this case, since ABOR for some reason only triggers when data is received on the data connection, so as long as no data is received the ABOR will hang. This is in itself another bug.

**Comment by glftpd** [comment] 2019-11-14 16:29
I guess you are mixing a few things together. Can you please poke Hujer on efnet #glftpd ?

I will try to look at ABOR if i have time but im somewhat confused about the other things.

**Comment by steakboy7000** [comment] 2019-11-26 20:17
I made a script for easily reproducing the problem, available here: https://cbftp.eu/glftpd-disconnect-transfer-persists.py

**Comment by glftpd** [comment] 2019-11-27 16:31
Thanks, i investigated it a bit already and the issue is quite simple. Since gl is single thread it will try to read data from the data conn after STOR. The timeout is set for 120seconds and during this it doesnt care what happens in control conn. Ill play around with it to see if something can be done without having to do a big mess.

**Comment by glftpd** [comment] 2019-12-02 00:43
will be fixed in next beta. gl will now check the status every second

**Closed as completed** 2019-12-02 00:42 UTC
